export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";

export const META_LIST_LOADING = "META_LIST_LOADING";
export const META_LIST_SUCCESS = "META_LIST_SUCCESS";
export const META_LIST_FAILURE = "META_LIST_FAILURE";

export const ADD_PATCH_LOADING = "ADD_PATCH_LOADING";
export const ADD_PATCH_SUCCESS = "ADD_PATCH_SUCCESS";
export const ADD_PATCH_FAILURE = "ADD_PATCH_FAILURE";

export const UPLOAD_PATCH_LOADING = "UPLOAD_PATCH_LOADING";
export const UPLOAD_PATCH_SUCCESS = "UPLOAD_PATCH_SUCCESS";
export const UPLOAD_PATCH_FAILURE = "UPLOAD_PATCH_FAILURE";

export const UPLOAD_PATCH_IMG_LOADING = "UPLOAD_PATCH_IMG_LOADING";
export const UPLOAD_PATCH_IMG_SUCCESS = "UPLOAD_PATCH_IMG_SUCCESS";
export const UPLOAD_PATCH_IMG_FAILURE = "UPLOAD_PATCH_IMG_FAILURE";

export const ADD_FILE_TO_UPLOAD = "ADD_FILE_TO_UPLOAD";
export const ADD_IMAGE_TO_UPLOAD = "ADD_IMAGE_TO_UPLOAD";
export const UPDATE_FILE_UPLOAD_PROGRESS = "UPDATE_FILE_UPLOAD_PROGRESS";

export const SEARCH_PATCH_LOADING = "SEARCH_PATCH_LOADING";
export const SEARCH_PATCH_SUCCESS = "SEARCH_PATCH_SUCCESS";
export const SEARCH_PATCH_FAILURE = "SEARCH_PATCH_FAILURE";

export const FETCH_USER_PATCHES_LOADING = "FETCH_USER_PATCHES_LOADING";
export const FETCH_USER_PATCHES_SUCCESS = "FETCH_USER_PATCHES_SUCCESS";
export const FETCH_USER_PATCHES_FAILURE = "FETCH_USER_PATCHES_FAILURE";

export const GET_PATCH_BY_ID_LOADING = "GET_PATCH_BY_ID_LOADING";
export const GET_PATCH_BY_ID_SUCCESS = "GET_PATCH_BY_ID_SUCCESS";
export const GET_PATCH_BY_ID_FAILURE = "GET_PATCH_BY_ID_FAILURE";

export const SELECT_PATCH = "SELECT_PATCH";
