export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";

export const META_LIST_LOADING = "META_LIST_LOADING";
export const META_LIST_SUCCESS = "META_LIST_SUCCESS";
export const META_LIST_FAILURE = "META_LIST_FAILURE";

export const ADD_PATCH_LOADING = "ADD_PATCH_LOADING";
export const ADD_PATCH_SUCCESS = "ADD_PATCH_SUCCESS";
export const ADD_PATCH_FAILURE = "ADD_PATCH_FAILURE";

export const ADD_VERSION_LOADING = "ADD_VERSION_LOADING";
export const ADD_VERSION_SUCCESS = "ADD_VERSION_SUCCESS";
export const ADD_VERSION_FAILURE = "ADD_VERSION_FAILURE";

export const UPLOAD_PATCH_LOADING = "UPLOAD_PATCH_LOADING";
export const UPLOAD_PATCH_SUCCESS = "UPLOAD_PATCH_SUCCESS";
export const UPLOAD_PATCH_FAILURE = "UPLOAD_PATCH_FAILURE";

export const UPLOAD_PATCH_IMG_LOADING = "UPLOAD_PATCH_IMG_LOADING";
export const UPLOAD_PATCH_IMG_SUCCESS = "UPLOAD_PATCH_IMG_SUCCESS";
export const UPLOAD_PATCH_IMG_FAILURE = "UPLOAD_PATCH_IMG_FAILURE";

export const ADD_FILE_TO_UPLOAD = "ADD_FILE_TO_UPLOAD";
export const ADD_IMAGE_TO_UPLOAD = "ADD_IMAGE_TO_UPLOAD";
export const UPDATE_FILE_UPLOAD_PROGRESS = "UPDATE_FILE_UPLOAD_PROGRESS";

export const SEARCH_PATCH_LOADING = "SEARCH_PATCH_LOADING";
export const SEARCH_PATCH_SUCCESS = "SEARCH_PATCH_SUCCESS";
export const SEARCH_PATCH_FAILURE = "SEARCH_PATCH_FAILURE";

export const FETCH_USER_PATCHES_LOADING = "FETCH_USER_PATCHES_LOADING";
export const FETCH_USER_PATCHES_SUCCESS = "FETCH_USER_PATCHES_SUCCESS";
export const FETCH_USER_PATCHES_FAILURE = "FETCH_USER_PATCHES_FAILURE";

export const GET_PATCH_BY_ID_LOADING = "GET_PATCH_BY_ID_LOADING";
export const GET_PATCH_BY_ID_SUCCESS = "GET_PATCH_BY_ID_SUCCESS";
export const GET_PATCH_BY_ID_FAILURE = "GET_PATCH_BY_ID_FAILURE";

export const UPDATE_PATCH_LOADING = "UPDATE_PATCH_LOADING";
export const UPDATE_PATCH_SUCCESS = "UPDATE_PATCH_SUCCESS";
export const UPDATE_PATCH_FAILURE = "UPDATE_PATCH_FAILURE";

export const UPDATE_VERSION_LOADING = "UPDATE_VERSION_LOADING";
export const UPDATE_VERSION_SUCCESS = "UPDATE_VERSION_SUCCESS";
export const UPDATE_VERSION_FAILURE = "UPDATE_VERSION_FAILURE";

export const GET_PATCH_VERSIONS_LOADING = "GET_PATCH_VERSIONS_LOADING";
export const GET_PATCH_VERSIONS_SUCCESS = "GET_PATCH_VERSIONS_SUCCESS";
export const GET_PATCH_VERSIONS_FAILURE = "GET_PATCH_VERSIONS_FAILURE";

export const GET_PATCH_VERSION_LOADING = "GET_PATCH_VERSION_LOADING";
export const GET_PATCH_VERSION_SUCCESS = "GET_PATCH_VERSION_SUCCESS";
export const GET_PATCH_VERSION_FAILURE = "GET_PATCH_VERSION_FAILURE";

export const DELETE_PATCH_LOADING = "DELETE_PATCH_LOADING";
export const DELETE_PATCH_SUCCESS = "DELETE_PATCH_SUCCESS";
export const DELETE_PATCH_FAILURE = "DELETE_PATCH_FAILURE";

export const DELETE_VERSION_LOADING = "DELETE_VERSION_LOADING";
export const DELETE_VERSION_SUCCESS = "DELETE_VERSION_SUCCESS";
export const DELETE_VERSION_FAILURE = "DELETE_VERSION_FAILURE";
